### ISSUE TITLE
Seeking documentation on how to use this with a reader over i2c

### ISSUE THREAD

**Issue by zacck-zz** [mchesser/llrp-rs#1]
Would it be possible to get pointers on how to use this library to operate an RFID reader specifically a SL3S4021 from NXP. I'm more than willing to contribute documentation from anything learned in the pointers. Thank you so much 🙏🏾

**Comment by mchesser** [comment]
Hi. Looking at the datasheet for the SL3S4021, the I<sup>2</sup>C interface doesn't actually use the LLRP protocol so this crate is probably not what you are looking for.

**Comment by zacck-zz** [comment]
@mchesser  oh that makes sense since I could not seem to link how it works together with LLRP, Would you mind if I asked you for pointers on what I need to understand in order to operate the SL3S4021? In all honesty my issue is not being able to find which registers I should send EPC Global commands to, I am willing to pay for your time for this if possible just been so stuck and I cant find my way past this
